const {createClient}=window.supabase;const sb=createClient(window.SUPABASE_CONFIG.url,window.SUPABASE_CONFIG.publishableKey);const $=id=>document.getElementById(id);let rows=[];
async function checkSession(){const {data:{session}}=await sb.auth.getSession();if(session)await showDashboard();else $('loginCard').hidden=false}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='Ingresando...';const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginMsg').textContent=error.message;return}await showDashboard()});
$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};$('refresh').onclick=loadData;$('search').oninput=render;$('filter').onchange=render;
async function showDashboard(){const {data:{user}}=await sb.auth.getUser();if(!user){location.reload();return}const {data:isAdmin,error}=await sb.rpc('is_admin');if(error||isAdmin!==true){$('loginCard').hidden=false;$('dashboard').hidden=true;$('loginMsg').textContent='Usuario sin permisos de administrador.';await sb.auth.signOut();return}$('loginCard').hidden=true;$('dashboard').hidden=false;await loadData()}
async function loadData(){$('dashMsg').textContent='Cargando...';const {data,error}=await sb.from('raffle_numbers').select('number,status,participant_id,reserved_at,paid_at,participants(name,phone)').order('number');if(error){$('dashMsg').textContent=error.message;return}rows=data||[];updateStats();render();$('dashMsg').textContent=''}
function updateStats(){const a=rows.filter(x=>x.status==='available').length,r=rows.filter(x=>x.status==='reserved').length,p=rows.filter(x=>x.status==='paid').length;$('available').textContent=a;$('reserved').textContent=r;$('paid').textContent=p;$('money').textContent=`$${p}`}
function render(){const q=$('search').value.toLowerCase().trim(),f=$('filter').value;const list=rows.filter(x=>{if(f!=='all'&&x.status!==f)return false;const p=x.participants;return !q||String(x.number).includes(q)||(p?.name||'').toLowerCase().includes(q)||(p?.phone||'').includes(q)});$('tbody').innerHTML=list.length?list.map(x=>{const p=x.participants,date=x.reserved_at?new Date(x.reserved_at).toLocaleString('es-EC'):'—';let action='—';if(x.status==='reserved')action=`<button class="action" onclick="markPaid(${x.number})">Marcar pagado</button><button class="action danger" onclick="releaseNumber(${x.number})">Liberar</button>`;else if(x.status==='paid')action=`<button class="action danger" onclick="releaseNumber(${x.number})">Liberar</button>`;return `<tr><td><strong>${String(x.number).padStart(3,'0')}</strong></td><td>${esc(p?.name||'—')}</td><td>${esc(p?.phone||'—')}</td><td><span class="badge ${x.status}">${x.status==='reserved'?'RESERVADO':x.status==='paid'?'PAGADO':'DISPONIBLE'}</span></td><td>${date}</td><td>${action}</td></tr>`}).join(''):'<tr><td colspan="6" class="empty">No hay resultados.</td></tr>'}
async function markPaid(number){if(!confirm(`¿Confirmar pago del número ${String(number).padStart(3,'0')}?`))return;const {error}=await sb.rpc('admin_mark_paid',{p_number:number});if(error){alert(error.message);return}await loadData()}
async function releaseNumber(number){if(!confirm(`¿Liberar el número ${String(number).padStart(3,'0')}? Esta acción elimina su asignación.`))return;const {error}=await sb.rpc('admin_release_number',{p_number:number});if(error){alert(error.message);return}await loadData()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}checkSession();
